### ISSUE TITLE
Create specific capabilities for BuddyDrive

### ISSUE THREAD

**Issue by imath** [imath/buddydrive#12]
Plugin severly lacks some capability checking.loggedin users are be able to upload files. It's the only check. Providing capabilities will allow it to be filtered and admins could restrict uploads to a specific role capability.

**Comment by imath** [comment]
See https://wordpress.org/support/topic/is-possible-a-supervisor-role-can-see-users-private-files-in-frontend

**Comment by robmcclel** [comment]
I am on board with this -- it was what I was going to recommend.  I think that in the Group Settings, the Group Admin should be able to restrict who can add files and who can't by role.  I know for my application, I only want Admins, possibly Moderators, to be able to add files.

**Comment by imath** [comment]
Thanks for your comment, i wasn't necessarily thinking about this, but when i'll build these capabilities (a bit like the one i've built in WP Idea Stream) it will be possible to easily extend it to match your need :)
