### ISSUE TITLE
Please make translations update savvy

### ISSUE THREAD

**Issue by schwarzaufweiss** [imath/buddydrive#3]
With BuddyPress 2.1 the language file is now update savvy (located in /wp-content/languages/plugins) – with BuddyDrive 1.2.1 that's not working, the language file has to be in the plugin directory itself (/wp-content/plugins/buddydrive/languages).
Please change BuddyDrive so that it's also update savvy. Thanks!

**Comment by imath** [comment]
FYI : 
```/wp-content/languages/plugins``` is for automatted translation upgrade.

You'll be able to use this location when 1.2.2 will be released. But you will also be able to use another location just in case BuddyDrive is one day benefiting from automatted translation upgrades and you need an alternative translation..

```/wp-content/languages/buddydrive```
