### ISSUE TITLE
Overwriting BuddyDrive Templates in Theme Directory

### ISSUE THREAD

**Issue by Samsonator** [imath/buddydrive#34]
I was wondering if it was possible, how to override the BuddyDrive /templates/ folder files in my theme directory so that I can safely edit the markup of the BuddyDrive page on my Member Single page.

I did a bit of debugging and I realised that it is loading the /members/single/plugins.php template from the BuddyPress files that I already have in my theme. I am just not sure of the correct way to include the BuddyDrive templates here and edit the markup.

As an example I am looking to rearrange the BuddyDrive page to look something similar to this: 
![buddydrive-design](https://cloud.githubusercontent.com/assets/796158/8575369/8b617a44-2593-11e5-8fc3-f1c9cf81b659.png)

Any help with this would be much appreciated!

Kind regards,
Sam

**Comment by imath** [comment]
Have you tried to copy wp-content/plugins/buddydrive/templates/buddydrive-entry.php and wp-content/plugins/buddydrive/templates/buddydrive-loop.php inside the ```buddypress``` folder of your theme

**Comment by Samsonator** [comment]
Thanks for replying! Yes copying those files worked thank you. I couldn't find an answer from googling the issue so hopefully someone else has the same issue and this helps them.
