### ISSUE TITLE
Loading BuddyDrive editor via ajax

### ISSUE THREAD

**Issue by MrVibe** [imath/buddydrive#39]
Great work with the Buddydrive editor. 
How to load Buddydrive editor via ajax ?

Tried adding a WP Editor with BuddyDrive_editor function with editor id, but it does not seem to work.

**Comment by imath** [comment]
I don't think it's possible because it needs to add javascripts into the footer. For a WP Editor, you don't need the id.

**Comment by MrVibe** [comment]
I tried adding the scripts manually, but the buddydrive container isn't loading. 
Refer screenshot : http://prntscr.com/89hwar

**Comment by imath** [comment]
That's because the content is populated during page load. I'm sorry i think you'll need another tool for your need.

**Comment by MrVibe** [comment]
Ok. Thanks for help :)
IMO, it would would be a great addition to Buddydrive.

**Comment by imath** [comment]
i guess, but when i'll have some more time i'll look at it. I think this can be done by including the button by default and hiding it, and when the wp_editor is ajax loaded, then show the button.
