### ISSUE TITLE
Restrict sharing options

### ISSUE THREAD

**Issue by imath** [imath/buddydrive#4]
See https://wordpress.org/support/topic/document-sharing-options-only-show-choose-the-group

As this is mostly done threw AJAX, should use wp_localiz_script() with a filterable array.

**Comment by jescoboza** [comment]
When I'm in BuddyDrive on the front end, the New File button and the New Folder Button are not working.  It will not let  me add a new folder nor a new file.  What can I do to fix this?

Joey

**Comment by risk00** [comment]
@imath, can you provide some guidance on how to implement this option? I'm using BuddyDrive 1.3.3.

What I'm trying to achieve is limiting share options to groups. Please see this [post from the WP Forum](https://wordpress.org/support/topic/document-sharing-options-only-show-choose-the-group).

Thank you in advance.

**Comment by imath** [comment]
@risk00 You can just put the content of the snippet i've shared into a bp-custom.php file See BuddyPress codex for infos about how to add this specific file.

On a side note, it's a bad idea to restrict to only groups imho.
