### ISSUE TITLE
Custom fields hidden while editing BuddyDrive files

### ISSUE THREAD

**Issue by MrVibe** [imath/buddydrive#43]
I have added Custom Step in BuddyDrive Fields and have been able to successfully saving them in post meta table via Buddydrive_meta fields through Buddydrive ajax.
Now, when I edit the Buddydrive files, there is a static "hide" class already attached to the custom field on line 543 of buddydrive-item-ajax.php which hides all the custom fields on editing the file. 
It works well while adding a new file because the hide class is removed, but on editing the file, all the fields are displayed at once and the hide class hides all the custom fields.

For now I've been able to by pass this by adding custom js 

`if($_POST['action'] == 'buddydrive_editform'){
				echo '<script>jQuery(document).ready(function($){$(".buddydrive-step").removeClass("hide");});</script>';
			}`
but it should be handled in the plugin itself.

**Comment by imath** [comment]
Thanks for your feedback, i'll look at it asap.
