### ISSUE TITLE
Custom Filter to customise the WP Query

### ISSUE THREAD

**Issue by MrVibe** [imath/buddydrive#44]
I've been trying to customise BuddyDrive get query by sending query parameters "buddydrive_scope" via the querystring filter. The scope parameter is great but not enough if one requires more than one variable to get the buddydrive attachments. 
It would allow a lot of freedom for developers , if you can add a filter on the $query_args parameter just before the WP_Query is performed in BuddyDrive_Item class.

Let me know if I missed something...

**Comment by MrVibe** [comment]
Let me know if you accept pull requests.

**Comment by imath** [comment]
Sure, i'll look at your pull request #45 asap
