### ISSUE TITLE
Add a new filter to restrict groups the user can publish items into

### ISSUE THREAD

**Issue by imath** [imath/buddydrive#57]
See https://wordpress.org/support/topic/allow-group-mods-and-admin-to-share-files-folders-in-group

**Comment by imath** [comment]
Let's say you want to only allow group mods/admins to share BuddyDrive item into the groups, you can simply add the following snippet to a [bp-custom.php](https://codex.buddypress.org/themes/bp-custom-php/) file (**once version 1.3.4 will be released!**): 

```php
function restrict_to_group_adminmods( $groups, $user_id ) {
	if ( empty( $groups ) || empty( $user_id ) ) {
		return $groups;
	}

	foreach ( $groups as $g => $group ) {
		if ( ! groups_is_user_admin( $user_id, $group->id ) && ! groups_is_user_mod( $user_id, $group->id ) ) {
			unset( $groups[ $g ] );
		}
	}
	return $groups;
}
add_filter( 'buddydrive_filter_select_user_group', 'restrict_to_group_adminmods', 10, 2 );
```

**Comment by robmcclel** [comment]
Hmmm...  I'm gonna check this out.
