### ISSUE TITLE
File names consisting only of numbers are displayed as "f-" in the list

### ISSUE THREAD

**Issue by geonom** [imath/buddydrive#59]
Testing the 2.0 beta version:

Uploaded four test files named
1.pdf
1n.pdf
n.pdf
n1.pdf

Except for the first one, the filenames of all others were shown correctly in the BuddyDrive Group Interface 
![test buddydrive filenames](https://cloud.githubusercontent.com/assets/1165081/14762001/109a9284-0970-11e6-9fcb-8ae63acc83df.png)

When I download the file, it still retains its original filename "1.pdf", so it seems to only be an issue with displaying the name?

P.S.:
Thanks so much for implementing the group sharing feature! One hundred thumbs up for your work, it is going to help us tons in setting up a new community :)

**Comment by imath** [comment]
Hi @geonom 

First i'd like to say a big "THANK YOU" for testing BuddyDrive 2.0.0-beta1. You are the first to report a bug and it's so great to have some help to make sure this new release will behave the right way.

Now, i'll explain a bit the 'f-' prefix in case the file name is made of numbers only. This is something that is there for quite a long time in BuddyDrive. If you test 1.3.3 you'll see that your file will also be prefixed.

I'm doing this to be sure downloading the file will be fine as if it's a numeric title, the function will try to get a BuddyFile post type having an ID of 1.

But you actually found a bug/regression from 1.3.3. The filename shouldn't be 'f-' but 'f-1' in your test. So i'll commit in a few seconds to fix this regression in 2.0.0-beta1.

Thanks again for your help.

**Comment by geonom** [comment]
Ah, thank you for the explanation, that makes sense.

Can confirm that the fix works correctly :)

If I find anything else, I'll let you know.

Thank you!
