### ISSUE TITLE
Ability to move files between folders

### ISSUE THREAD

**Issue by slaFFik** [imath/buddydrive#65]
Would be a neat feature.

**Comment by imath** [comment]
It's actually possible, as long as you are the owner of the parent folder. You just need to edit the file.
![unattach](https://cloud.githubusercontent.com/assets/1834524/14994497/8698c8ae-1170-11e6-967f-852f1c1352d1.png)

![attach](https://cloud.githubusercontent.com/assets/1834524/14994508/90153cdc-1170-11e6-9bfd-19a4d9449ccc.png)
